version: 2
multi-ecosystem-groups:
  weekly-dependencies:
    schedule:
      interval: "weekly"
      day: "monday"

updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-dependencies"
    open-pull-requests-limit: 5

  - package-ecosystem: "uv"
    directories:
      - "/"
      - "/backend/common"
      - "/backend/pipelines/*"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-dependencies"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-dependencies"
    open-pull-requests-limit: 5
