name: Deploy Cadastral Sync

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

env:
  PROJECT_ID: landbrugsdata-1
  SERVICE_NAME: cadastral-sync
  REGION: europe-west1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Build and Push Container
      run: |
        cd backend
        gcloud builds submit --config cloudbuild.yaml . --quiet

    - name: Check Build Status
      run: |
        BUILD_ID=$(gcloud builds list --limit=1 --format='value(id)')
        while true; do
          STATUS=$(gcloud builds describe $BUILD_ID --format='value(status)')
          if [ "$STATUS" = "SUCCESS" ]; then
            echo "Build completed successfully"
            break
          elif [ "$STATUS" = "FAILURE" ] || [ "$STATUS" = "CANCELLED" ]; then
            echo "Build failed with status: $STATUS"
            exit 1
          fi
          echo "Build status: $STATUS"
          sleep 10
        done

    - name: Deploy Cloud Run Job
      run: |
        gcloud run jobs update $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
          --region $REGION \
          --service-account github@$PROJECT_ID.iam.gserviceaccount.com \
          --set-secrets=DB_PASSWORD=db-password:latest,DATAFORDELER_USERNAME=datafordeler-username:latest,DATAFORDELER_PASSWORD=datafordeler-password:latest \
          --set-env-vars=DB_HOST=/cloudsql/$PROJECT_ID:$REGION:landbrugsdata-db,DB_NAME=landbrugsdata,DB_USER=landbrugsdata \
          --cpu=2 \
          --memory=4Gi \
          --max-retries=3 \
          --task-timeout=2h || \
        gcloud run jobs create $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
          --region $REGION \
          --service-account github@$PROJECT_ID.iam.gserviceaccount.com \
          --set-secrets=DB_PASSWORD=db-password:latest,DATAFORDELER_USERNAME=datafordeler-username:latest,DATAFORDELER_PASSWORD=datafordeler-password:latest \
          --set-env-vars=DB_HOST=/cloudsql/$PROJECT_ID:$REGION:landbrugsdata-db,DB_NAME=landbrugsdata,DB_USER=landbrugsdata \
          --cpu=2 \
          --memory=4Gi \
          --max-retries=3 \
          --task-timeout=2h
