name: Validate Mage.ai Pipeline Configuration

on:
  push:
    paths:
      - 'backend/mage/**'
      - '.github/workflows/mage-pipeline-validation.yml'
  pull_request:
    paths:
      - 'backend/mage/**'
      - '.github/workflows/mage-pipeline-validation.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/mage

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Lint with ruff
        run: |
          ruff check .
          ruff format --check .

  docker:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend/mage
          push: false
          load: true
          tags: mageai-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max 