name: Sync and Deploy

on:
  schedule:
    - cron: '0 2 * * 1'  # Runs at 2 AM UTC every Monday
  workflow_dispatch:      # Allows manual trigger
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
    
env:
  PROJECT_ID: landbrugsdata-1
  REGION: europe-west1
  
jobs:
  sync-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Google Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - name: Build and Deploy
      run: |
        cd backend
        gcloud builds submit --tag gcr.io/$PROJECT_ID/agricultural-api
        gcloud run deploy agricultural-api \
          --image gcr.io/$PROJECT_ID/agricultural-api \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated
