name: Sync and Deploy

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM UTC daily
  workflow_dispatch:      # Allows manual trigger
  push:
    branches: [ main ]
    
env:
  PROJECT_ID: landbrugsdata-1
  REGION: europe-west1
  
jobs:
  sync-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Google Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - name: Create Dockerfile
      run: |
        cat << 'EOF' > backend/Dockerfile
        FROM python:3.9-slim

        # Install system dependencies
        RUN apt-get update && apt-get install -y \
            gdal-bin \
            libgdal-dev \
            gcc \
            python3-dev \
            g++ \
            && rm -rf /var/lib/apt/lists/*

        # Set GDAL environment variables
        ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
        ENV C_INCLUDE_PATH=/usr/include/gdal

        # Set working directory
        WORKDIR /app

        # Copy requirements first for better caching
        COPY requirements.txt .

        # Install Python dependencies
        RUN pip install --no-cache-dir -r requirements.txt

        # Copy the rest of the application
        COPY . .

        # Command to run the application
        CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
        EOF
    
    - name: Deploy to Cloud Run
      id: deploy
      run: |
        gcloud run deploy geodata-api \
          --source backend \
          --region $REGION \
          --allow-unauthenticated \
          --platform managed \
          --verbosity=debug
    
    - name: View Build Logs
      if: failure()
      run: |
        BUILD_ID=$(gcloud builds list --limit=1 --format='value(id)')
        gcloud builds log $BUILD_ID
