name: Sync Cadastral Data

on:
  schedule:
    - cron: '0 2 * * 1'  # Runs at 2 AM UTC every Monday
  workflow_dispatch:      # Allows manual triggers

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install GDAL
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        
    - name: Run cadastral sync
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        DATAFORDELER_USERNAME: ${{ secrets.DATAFORDELER_USERNAME }}
        DATAFORDELER_PASSWORD: ${{ secrets.DATAFORDELER_PASSWORD }}
      run: |
        cd backend
        python scripts/sync_cadastral.py 